### PR TITLE
Using abspath, and add docstring, add tqdm flag

### PR DESCRIPTION
**Pull request by vaaaaanquish**
https://github.com/m3dev/thunderbolt/issues/5

### CODE REVIEW

**Comment by vaaaaanquish** [comment]
@nishiba @hirosassa Please check PR.

**Comment by vaaaaanquish** [comment]
This has also been resolved : https://github.com/m3dev/thunderbolt/issues/7

**Comment by hirosassa** [comment]
Good improvement about docstrings! LGTM

**Comment by nishiba** [comment]
LGTM

**Pull request merged**
